default:
  age_expand: !expr 3:18

jiaokeyuan:
  where:
    base_organization:
      Name:
      - 成都金苹果公学
      - 成都市温江区鹏程小学
      - 成都市东城根街小学
      - 成都市龙江路小学
      - 都江堰市聚源小学
      - 华阳中学附属小学
      - 成都市人北实验小学
      - 成都经济技术开发区实验小学
      - 成都市青白江区实验小学
      - 成都市新都区旃檀小学
      - 成都墨池书院小学
      - 成都市双流区实验小学
      - 成都市锦江区外国语小学
      - 简阳中学
      - 崇庆中学实验学校
      - 成都市第五十二中学
      - 北师大成都实验中学
      - 成都教科院附属学校（初中部）
    course:
      Name:
      - 大脑学习力快速测试（小学低年级）
      - 大脑学习力快速测试（小学高年级）
      - 初中生大脑学习能力快速测试
