default:
  # use params to explicitly declare all the variables used when kniting
  report.params:
    title: 大脑学习能力测评
    subtitle: 集体报告
    ability_info:
      code: [Att, Mem, SC, Rsn, RT]
      name: [注意力, 记忆力, 自控力, 思维力, 反应力]
      color: ["#fbbc05", "#34a853", "#ea4335", "#4285f4", "#b61285"]
      def:
      - 注意力是大脑接收和处理个体外部和内部信息的前提，只有被注意到的信息才能得到有有效的分析和处理才能用来解决问题并形成持久的记忆。注意力包含选择注意、持续注意和分配注意三个能力维度，本次施测下每个维度都有对应的施测题目，学生分数越高，代表注意力越集中。
      - 记忆力是人脑智力的集中体现，也是人脑比电脑更聪明的重要原因。个体的生存和发展需要不断掌握新的知识，记忆力能将这些 知识经验存储下来并合理运用。记忆连接着人的过去和未来，丰富着我们的精神生活并塑造着我们的性格。人脑包含复杂的记忆系统，其中联系记忆、语义记忆和短时记忆是三个重要的维度，每个维度都有对应的施测题目，学生分数越高，代表记忆力越好。
      - 自控力是人们能够根据目标和环境的要求，控制和改变自己的思想和行为，克服冲动并抵制诱惑，让自己的行为符合社会期许和长期目标的能力。自控力主要体现在控制冲动、抵制诱惑以及信息更新这三个维度，每个维度都有对应的施测题目，学生分数越高，代表自控力越强。
      - 思维力是人们接收到信息后，对信息进行归纳、概括及推理的过程。生活中，我们往往不满足于耳朵所听到的、眼睛所看到的，而是要找出事物之间的内在联系和规律，解决问题并创造出新的知识。思维力可以分为思维的灵活性、深刻性和独创性这三个维度，每个维度都有对应的施测题目，学生分数越高，代表思维力越强。
      - 反应力是对各种信息、要求和指令等做出快速反应的能力。速度是衡量反应力最重要的指标，它体现了大脑各个系统的协调、整合发展的水平，与整个神经网络的效率有密切关系。反应力可以从反应速度、言语速度和思维速度三个维度来测量。本次施测下每个维度都有对应的施测题目，学生分数越高，代表反应力越强。
    grade_order: !expr c("一年级", "二年级", "三年级", "四年级", "五年级", "六年级", "初一", "初二", "初三")
    score_level:
      breaks: !expr c(-Inf, 73, 79, 85, 91, 97, 103, 109, 115, 121, 127, Inf)
      labels: !expr c("D", "C-", "C", "C+", "B-", "B", "B+", "A-", "A", "A+", "S")

jiaokeyuan:
  report.params:
    customer_name: 成都教育科学院
  where:
    base_organization:
      Name:
      - 成都金苹果公学
      - 成都市温江区鹏程小学
      - 成都市东城根街小学
      - 成都市龙江路小学
      - 都江堰市聚源小学
      - 华阳中学附属小学
      - 成都市人北实验小学
      - 成都经济技术开发区实验小学
      - 成都市青白江区实验小学
      - 成都市新都区旃檀小学
      - 成都墨池书院小学
      - 成都市双流区实验小学
      - 成都市锦江区外国语小学
      - 简阳中学
      - 崇庆中学实验学校
      - 成都市第五十二中学
      - 北师大成都实验中学
      - 成都教科院附属学校（初中部）
    course:
      Name:
      - 大脑学习力快速测试（小学低年级）
      - 大脑学习力快速测试（小学高年级）
      - 初中生大脑学习能力快速测试
